### PR TITLE
Add Sandstorm packaging files

### PR DESCRIPTION
**Pull request by ocdtrekkie**
Related to https://github.com/openmicroapps/meta/issues/14, I am interested in any feedback, and whether or not I should maintain this as a fork or if you'd like to upstream it and host it directly.

This PR adds a .sandstorm directory which can build this app for Sandstorm.io servers. You can see a running example here:
Screenshot from 2020-07-23 21-30-05

After packaging, I placed the app package in the "experimental market" for testing: https://apps.sandstorm.io/app/p4z5hactgfhv2k5k845fvth60cnm78yn5k39r62jxwyzhrtqpn00?experimental=true

I think in an Open Micro Apps discussion, I saw it referred to as μTodo, so I used that as the app name in this case, to distinguish it from other todo apps available on Sandstorm. There's no changes to the functionality of the app, however, we move the database location to /var because Sandstorm apps operate in a predominantly read-only file system, except for /var.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
Also, here's a demo grain of the app, so you can see it live: https://ocdhost.sandcats.io:6080/shared/xtQxc4OQfOAWwJLrqP8Styyp8tlDm3xJcWkmAkr3pqp

**Comment by prologic** [comment]
I _think_ this is a great idea! I've not played with Sandstorm myself so I have no idea how all that works; but OpenMicroApps itself kinda/sorta went nowhere, so I pulled all the apps/repos I wrote back into my account. I'll have a look at your PR over the next coming days! Thank :)

**Comment by ocdtrekkie** [comment]
There's no code changes to your project, solely build scripts and metadata for Sandstorm packaging. My biggest request for feedback is on the app name and description. I do have one more adjustment to make to the metadata, where I selected the wrong image for one of the market fields. (If you look at https://apps.sandstorm.io/?experimental=true you'll notice the mTodo icon is super small compared to the other apps... oops.) When you review this PR, I'll fix that and incorporate any other notes you have before you merge. :)

I will also send an invite to your email to my personal Sandstorm server so you can see how Sandstorm works, and potentially test out these apps. Notes, pastebin, and wiki at minimum should package very cleanly for Sandstorm without any changes. I *think* we could package twtxt and Tube with existing platform features as well. The IRC apps are going to have to wait for future platform features though, Sandstorm doesn't yet provide a good method for an app to get access to an arbitrary network port.

**Comment by prologic** [comment]
> I will also send an invite to your email to my personal Sandstorm server so you can see how Sandstorm works, and potentially test out these apps. Notes, pastebin, and wiki at minimum should package very cleanly for Sandstorm without any changes. I think we could package twtxt and Tube with existing platform features as well. The IRC apps are going to have to wait for future platform features though, Sandstorm doesn't yet provide a good method for an app to get access to an arbitrary network port.

Ahh so that email I got wasn't spam :) *phew*

I'll have a look for sure, this all sounds great.

I just haven't played with Sandstorm myself.

I run all of my own (_non-trivial_) infra with Docker Swarm clusters and lots of tooling/auotmation.

**Comment by ocdtrekkie** [comment]
Considering @KevinNThomas's theme PR, I may add a Sandstorm-matching color theme in the next version of the Sandstorm package as well.

**Pull request merged**
