### PR TITLE
Update README and remove unused files

### PR DESCRIPTION
**Pull request by KevinNThomas**
Should probably only be merged after https://github.com/prologic/todo/pull/24, https://github.com/prologic/todo/pull/25, https://github.com/prologic/todo/pull/26, and https://github.com/prologic/todo/pull/27

The prologic/todo docker image should also probably be updated before merging this.

I have a wiki setup showing screenshots of all the preset color themes here: https://gitlab.com/KevinNThomas/2do/-/wikis/Color-Themes. If you want, you can enable the wiki for this repo and we can add that to the wiki and link it in the README.

### CODE REVIEW

**Comment by KevinNThomas** [comment]
Will update this with updated documentation next.

**Comment by KevinNThomas** [comment]
@prologic The demo page at https://todo.mills.io and the Docker image should probably be updated before merging this. Also, I made a wiki page on my repo a while ago showcasing screenshots of all the different preset color themes in both mobile and desktop views: https://gitlab.com/KevinNThomas/2do/-/wikis/Color-Themes If you enable a wiki for this repo, I can copy over the wiki page and add it to the README if you'd like.

**Comment by prologic** [comment]
Yes please! Done. I will try to update my instance soon! Thanks :D

**Comment by KevinNThomas** [comment]
@prologic Thank you! I think "Restrict edits to collaborators only" might still be checked for the wiki, as I can't seem to access it?

**Comment by prologic** [comment]
Fixed!

**Pull request merged**
